### PR TITLE
Resetting slave accumulators

### PR DESCRIPTION
**Pull request by galexv**
This is to fix issue #295: duplication on measurements by repeated collective_merge.
Autocorrelation values after repeated merge are not quite correct.

### CODE REVIEW

**Comment by egull** [comment]
ok, looks good to me. But as this is in response to @jgreitemann 's report I will solicit a review from him.

**Comment by jgreitemann** [comment]
Thanks for keeping me in the loop. The modifications look fine to me, however when running our code against it without the previously used workaround, I get some weird deadlock behavior when measuring a reset accumulator again. I suspect that's due to a problem on our end, but would like to understand what exactly is going on before greenlighting this PR. I'll probably have some time to investigate over the weekend.

**Comment by galexv** [comment]
@jgreitemann 
> I get some weird deadlock behavior when measuring a reset accumulator again

I have had a similar experience, so let me venture a guess that might help figuring out what could have happened:
The collective merge now clears the accumulators on slaves. If there is no data added to accumulators prior to the next collective merge, the merge detects empty accumulator on slaves and throws an exception. If the exception propagates to the top level, `alps::mpi::environment` calls `MPI_Abort()`.  If the exception is caught (for example, by GTest framework), this results in unmatched collective MPI call and MPI waiting forever, which looks like a deadlock.

**Comment by jgreitemann** [comment]
Thanks Alex, that is exactly what's happening. You saved me some pain there.

So, the exceptions stems from [this boost assert](https://github.com/ALPSCore/ALPSCore/blob/008bef5aaa93df92aff14a748b75e8c1c59cf3a6/accumulators/include/alps/accumulators/feature/binning_analysis.hpp#L267). I haven't been able to consistently reproduce it; there seems to be some delicate timing involved. In particular, I got the code to throw only when compiled with optimizations (which made debugging tricky), and from what I observed, it was always the master (rank 0) process that threw upon the first new measurement of any observable after some collective merges. I don't entirely understand the binning analysis code, but my best guess is that the `m_ac_partial` vector is not affected by the merge and that leads to problems when the binning level of the merged-in accumulator was higher than that of the accumulator on the master? Possibly the solution is as simple as adding something like `m_ac_partial.resize(m_ac_sum2.size());` after [line 356](https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/include/alps/accumulators/feature/binning_analysis.hpp#L356)?

Strictly speaking, this probably isn't related to this PR, it's only that the specific circumstances to produce this error didn't show up before. Why I don't get the same problem with my original workaround (where I called `wrapper_set::reset()` on the `measurements` member in `run` *after* `collect_results` is done) escapes me.

**Comment by egull** [comment]
Alex, could you please get this one done, too? Is there anything else holding it up?

**Comment by galexv** [comment]
I have to do some debugging to reproduce the behavior observed by Jonas, and fix it...

**Pull request merged**
