### PR TITLE
New GF fixes needed for inchworm code

### PR DESCRIPTION
**Pull request by krivenko**
I'll be pushing everything we need for InchwormHPX to this branch/PR.

### CODE REVIEW

**Comment by krivenko** [comment]
Ok, that's about all I needed to change.
Please, review, ask for changes and merge.

**Comment by egull** [comment]
sorry, approved the wrong one. Here is what I get:

[ 72%] Building CXX object gf/test/CMakeFiles/gf_new_test_mpi.dir/gf_new_test_mpi.cpp.o
In file included from /Users/egull/ALPSCore/gf/test/gf_new_test_mpi.cpp:10:
/Users/egull/ALPSCore/gf/include/alps/gf/gf_base.hpp:157:9: error: exception specification of explicitly defaulted move constructor
      does not match the calculated one
        gf_base(gf_type &&g) noexcept = default;
        ^
/opt/local/libexec/llvm-4.0/bin/../include/c++/v1/type_traits:1373:66: note: in instantiation of template class
      'alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2, alps::numerics::detail::data_view<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh>' requested here
    : public integral_constant<bool, __is_convertible_to(_T1, _T2) &&
                                                                 ^
/Users/egull/ALPSCore/gf/include/alps/gf/gf_base.hpp:432:40: note: in instantiation of template class
      'std::__1::is_convertible<alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2,
      alps::numerics::detail::data_storage<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh>,
      alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2, alps::numerics::detail::data_view<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh> >' requested here
                               || std::is_convertible < RHS_GF, generic_gf<data_view> >::value, bool >::type
                                       ^
/Users/egull/ALPSCore/common/deps/gtest-1.7.0/include/gtest/gtest.h:1448:16: note: while substituting deduced template arguments
      into function template 'operator==' [with RHS_GF = alps::gf::detail::gf_base<double,
      alps::numerics::detail::tensor_base<double, 2, alps::numerics::detail::data_storage<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh>]
  if (expected == actual) {
               ^
/Users/egull/ALPSCore/common/deps/gtest-1.7.0/include/gtest/gtest.h:1484:12: note: in instantiation of function template
      specialization 'testing::internal::CmpHelperEQ<alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double,
      2, alps::numerics::detail::data_storage<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh>,
      alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2, alps::numerics::detail::data_storage<double>
      >, alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh> >' requested here
    return CmpHelperEQ(expected_expression, actual_expression, expected,
           ^
/Users/egull/ALPSCore/gf/test/gf_new_test_mpi.cpp:47:5: note: in instantiation of function template specialization
      'testing::internal::EqHelper<false>::Compare<alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2,
      alps::numerics::detail::data_storage<double> >,
      alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh>,
      alps::gf::detail::gf_base<double, alps::numerics::detail::tensor_base<double, 2, alps::numerics::detail::data_storage<double>
      >, alps::gf::matsubara_mesh<alps::gf::mesh::frequency_positivity_type::POSITIVE_ONLY>, alps::gf::index_mesh> >' requested here
    ASSERT_EQ(gf3, gf);
    ^
/Users/egull/ALPSCore/common/deps/gtest-1.7.0/include/gtest/gtest.h:2011:32: note: expanded from macro 'ASSERT_EQ'
# define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
                               ^
/Users/egull/ALPSCore/common/deps/gtest-1.7.0/include/gtest/gtest.h:1994:67: note: expanded from macro 'GTEST_ASSERT_EQ'
                      EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                                                  ^
1 error generated.
make[2]: *** [gf/test/CMakeFiles/gf_new_test_mpi.dir/gf_new_test_mpi.cpp.o] Error 1
make[1]: *** [gf/test/CMakeFiles/gf_new_test_mpi.dir/all] Error 2
make: *** [all] Error 2
egull-mbp2:build_cpp11 egull$

**Comment by krivenko** [comment]
@egull Could you try to remove `noexcept` from `gf_base(gf_type &&g) noexcept = default`?

**Comment by egull** [comment]
works beautifully without the noexcept.

**Pull request merged**
