### PR TITLE
[alea] Add tutorial

### LINKED ISSUE #574: [alea] Add tutorial
Complaint by @krivenko , who considers it a blocker for the paper.

### PR DESCRIPTION
**Pull request by mwallerb**
Fixes #574 

@krivenko please look at this, for some reason I cannot add you as reviewer.

### CODE REVIEW

**Comment by mwallerb** [comment]
@egull Which changes are you requesting to this PR?

**Comment by mwallerb** [comment]
@egull I don't see how the webpage is connected to this code. Propose to merge this code and open a separate issue.

**Comment by egull** [comment]
Just do the web page before you close the issue and declare it done.

**Comment by mwallerb** [comment]
Wiki page there.

**Pull request merged**
