### PR TITLE
replace std::uncaught_exception() with std::uncaught_exceptions()

### PR DESCRIPTION
**Pull request by wistaria**

### CODE REVIEW

**Comment by egull** [comment]
Sergei, Have a look at this error on Intel:

[  4%] Building CXX object utilities/test/CMakeFiles/mpi_utils_bcast_optional.dir/mpi_utils_bcast_optional.cpp.o

In file included from /var/lib/jenkins/workspace/lic_projects_alpscore.old_PR-639@7/utilities/include/alps/utilities/mpi_optional.hpp(15),

                 from /var/lib/jenkins/workspace/lic_projects_alpscore.old_PR-639@7/utilities/test/mpi_utils_bcast_optional.cpp(7):

/var/lib/jenkins/workspace/lic_projects_alpscore.old_PR-639@7/utilities/include/alps/utilities/mpi.hpp(248): error: namespace "std" has no member "uncaught_exceptions"

                  if (abort_on_exception_ && std::uncaught_exceptions()) {

                                                  ^


In file included from /var/lib/jenkins/workspace/lic_projects_alpscore.old_PR-639@7/utilities/test/mpi_utils_env.cpp(7):

/var/lib/jenkins/workspace/lic_projects_alpscore.old_PR-639@7/utilities/include/alps/utilities/mpi.hpp(248): error: namespace "std" has no member "uncaught_exceptions"

                  if (abort_on_exception_ && std::uncaught_exceptions()) {

                                                  ^


[  4%] Linking CXX shared library libgtest_main.so

**Comment by iskakoff** [comment]
@egull 
`std::uncaught_exceptions` is introduced in c++17, so we cannot use this in ALPSCore unless we set current standard to be c++17.

**Comment by egull** [comment]
@iskakoff would be nice to bring this one to a definite state; either by fixing it or by finding a workaround that always works.

**Comment by iskakoff** [comment]
> @iskakoff would be nice to bring this one to a definite state; either by fixing it or by finding a workaround that always works.

added macro for that, should work now for pre and post c++20 compilers.

**Pull request closed without merging**
