### PR TITLE
Add Travis CI configuration file

### PR DESCRIPTION
**Pull request by krivenko**
Travis CI is a free continuous integration service that is easily connectable to GitHub repositories.
Repository admins can configure automatically triggered and scheduled builds of `master`, other/all branches and new pull requests.

### CODE REVIEW

**Comment by krivenko** [comment]
@egull Can Jenkins automatically build pull requests?

**Comment by egull** [comment]
I think so...
https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin
...but I have no preference, anything works.

**Comment by galexv** [comment]
We are sure there are no private repositories within ALPSCore organization, right? When i am going to to TravisCI, it happily requests access to whatever repos my userID has access to. I believe access can be limited by per-organization basis, not sure about per-repo basis.

(For cross-reference: issue #283)

**Comment by krivenko** [comment]
@galexv If you don't trust Travis CI, then this could be an issue, of course...
If your actual concern is about repositories being exposed to public, Travis CI will not disclose information about repositories, which are not enabled on the settings page.

For example: https://travis-ci.org/ALPSCore/CT-HYB

**Pull request merged**
